# Generated by Django 3.2.5 on 2021-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=128)),
                ('definition', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('sound', models.CharField(max_length=128)),
            ],
        ),
    ]
